export const ADD_NOTIFICATION_MESSAGE = "ADD_NOTIFICATION_MESSAGE";
export const REMOVE_NOTIFICATION_MESSAGE = "REMOVE_NOTIFICATION_MESSAGE";
export const NOTIFICATION_MESSAGE = "NOTIFICATION_MESSAGE";
export const CLEAR_NOTIFICATION_MESSAGE = "CLEAR_NOTIFICATION_MESSAGE";