export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";

export const MODAL_EXPENSE_ITEM_ADD = "MODAL_EXPENSE_ITEM_ADD";
// export const MODAL_EXPENSE_ITEM_ADD_AWAIT = "MODAL_EXPENSE_ITEM_ADD_AWAIT";
// export const MODAL_EXPENSE_ITEM_ADD_SUCCESS = "MODAL_EXPENSE_ITEM_ADD_SUCCESS";
// export const MODAL_EXPENSE_ITEM_ADD_ERROR = "MODAL_EXPENSE_ITEM_ADD_ERROR";

export const MODAL_EXPENSE_ITEM_EDIT = "MODAL_EXPENSE_ITEM_EDIT";
// export const MODAL_EXPENSE_ITEM_AWAIT = "MODAL_EXPENSE_ITEM_AWAIT";
// export const MODAL_EXPENSE_ITEM_SUCCESS = "MODAL_EXPENSE_ITEM_SUCCESS";
// export const MODAL_EXPENSE_ITEM_ERROR = "MODAL_EXPENSE_ITEM_ERROR";

export const MODAL_EXPENSE_ITEM_DELETE = "MODAL_EXPENSE_ITEM_DELETE";
// export const MODAL_EXPENSE_ITEM_DELETE_AWAIT = "MODAL_EXPENSE_ITEM_DELETE_AWAIT";
// export const MODAL_EXPENSE_ITEM_DELETE_SUCCESS = "MODAL_EXPENSE_ITEM_DELETE_SUCCESS";
// export const MODAL_EXPENSE_ITEM_DELETE_ERROR = "MODAL_EXPENSE_ITEM_DELETE_ERROR";

export const MODAL_COST_ADD = "MODAL_COST_ADD";
// export const MODAL_COST_ADD_AWAIT = "MODAL_COST_ADD_AWAIT ";
// export const MODAL_COST_ADD_SUCCESS = "MODAL_COST_ADD_SUCCESS";
// export const MODAL_COST_ADD_ERROR = "MODAL_COST_ADD_ERROR";

export const MODAL_SUPPORT = "MODAL_SUPPORT";