export const MODAL_CLOSE = "MODAL_CLOSE";
export const MODAL_CLEAR = "MODAL_CLEAR";

export const MODAL_EXPENSE_ITEM_ADD = "MODAL_EXPENSE_ITEM_ADD";

export const MODAL_EXPENSE_ITEM_EDIT = "MODAL_EXPENSE_ITEM_EDIT";

export const MODAL_EXPENSE_ITEM_DELETE = "MODAL_EXPENSE_ITEM_DELETE";

export const MODAL_COST_ADD = "MODAL_COST_ADD";

export const MODAL_SUPPORT = "MODAL_SUPPORT";

export const MODAL_MAIN_MENU = "MODAL_MAIN_MENU";

export const MODAL_COSTS_COLLECTION = "MODAL_COSTS_COLLECTION";

export const MODAL_DELETE_COST_IN_COLLECTION = "MODAL_DELETE_COST_IN_COLLECTION";

export const MODAL_EDIT_COST_IN_COLLECTION = "MODAL_EDIT_COST_IN_COLLECTION";