export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";

export const MODAL_EXPENSE_ITEM_ADD = "MODAL_EXPENSE_ITEM_ADD";

export const MODAL_EXPENSE_ITEM_EDIT = "MODAL_EXPENSE_ITEM_EDIT";

export const MODAL_EXPENSE_ITEM_DELETE = "MODAL_EXPENSE_ITEM_DELETE";

export const MODAL_COST_ADD = "MODAL_COST_ADD";

export const MODAL_SUPPORT = "MODAL_SUPPORT";

export const MODAL_MAIN_MENU = "MODAL_MAIN_MENU";