export const PUSH_MESSAGE_TO_SUPPORT = "PUSH_MESSAGE_TO_SUPPORT";
export const AWAIT_PUSH_MESSAGE_TO_SUPPORT = "AWAIT_PUSH_MESSAGE_TO_SUPPORT";
export const SUCCESS_PUSH_MESSAGE_TO_SUPPORT = "SUCCESS_PUSH_MESSAGE_TO_SUPPORT";
export const ERROR_PUSH_MESSAGE_TO_SUPPORT = "ERROR_PUSH_MESSAGE_TO_SUPPORT";