export const GET_COSTS = "GET_COSTS";
export const AWAIT_REQUEST_COSTS = "AWAIT_REQUEST_COSTS";
export const SUCCESS_REQUEST_COSTS = "SUCCESS_REQUEST_COSTS";
export const ERROR_REQUEST_COSTS = "ERROR_REQUEST_COSTS";

export const ADD_COSTS = "ADD_COSTS";
export const AWAIT_ADD_COSTS = "AWAIT_ADD_COSTS";
export const SUCCESS_ADD_COSTS = "SUCCESS_ADD_COSTS";
export const ERROR_ADD_COSTS = "ERROR_ADD_COSTS";

export const EDIT_COST = "EDIT_COST";

export const ADD_EXPENSE_ITEM = "ADD_EXPENSE_ITEM";
export const AWAIT_ADD_EXPENSE_ITEM = "AWAIT_ADD_EXPENSE_ITEM";
export const SUCCESS_ADD_EXPENSE_ITEM = "SUCCESS_ADD_EXPENSE_ITEM";
export const ERROR_ADD_EXPENSE_ITEM = "ERROR_ADD_EXPENSE_ITEM";

export const DELETE_EXPENSE_ITEM = "DELETE_EXPENSE_ITEM";
export const AWAIT_DELETE_EXPENSE_ITEM = "AWAIT_DELETE_EXPENSE_ITEM";
export const SUCCESS_DELETE_EXPENSE_ITEM = "SUCCESS_DELETE_EXPENSE_ITEM";
export const ERROR_DELETE_EXPENSE_ITEM = "ERROR_DELETE_EXPENSE_ITEM";

export const CHANGE_EXPENSE_ITEM = "CHANGE_EXPENSE_ITEM";
export const AWAIT_CHANGE_EXPENSE_ITEM = "AWAIT_CHANGE_EXPENSE_ITEM";
export const SUCCESS_CHANGE_EXPENSE_ITEM = "SUCCESS_CHANGE_EXPENSE_ITEM";
export const ERROR_CHANGE_EXPENSE_ITEM = "ERROR_CHANGE_EXPENSE_ITEM";