export const AWAIT_REQUEST_COSTS = "AWAIT_REQUEST_COSTS";
export const SUCCESS_REQUEST_COSTS = "SUCCESS_REQUEST_COSTS";
export const ERROR_REQUEST_COSTS = "ERROR_REQUEST_COSTS";

export const GET_COSTS = "GET_COSTS";
export const ADD_COSTS = "ADD_COSTS";
// export const CANCEL_COSTS = "CANCEL_COSTS";

export const ADD_EXPENSE_ITEM = "ADD_EXPENSE_ITEM";
export const DELETE_EXPENSE_ITEM = "DELETE_EXPENSE_ITEM";
export const CHANGE_EXPENSE_ITEM = "CHANGE_EXPENSE_ITEM";