export const MAIN_MENU_CHANGE_PASSWORD = "MAIN_MENU_CHANGE_PASSWORD";
export const MAIN_MENU_MY_DATA = "MAIN_MENU_MY_DATA";
export const MAIN_MENU_LOGOUT = "MAIN_MENU_LOGOUT";
export const MAIN_MENU_LIST = "MAIN_MENU_LIST";