export const COSTS_COLLECTION_SUCCESS = "COSTS_COLLECTION_SUCCESS";
export const COSTS_COLLECTION_ERROR = "COSTS_COLLECTION_ERROR";
export const COSTS_COLLECTION_AWAIT = "COSTS_COLLECTION_AWAIT";

export const GET_COSTS_COLLECTION = "GET_COSTS_COLLECTION";